### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by rogermartensson** [Hyperchalk/Hyperchalk#1]
Is it possible to change the used language without creating a custom image?

**Comment by onemenzel** [comment]
Yes, via the settings key `LANGUAGE_CODE`. It isn't accessible via an environment variable, yet.

**Comment by onemenzel** [comment]
fixed in [3cc6a2b](https://github.com/Hyperchalk/Hyperchalk/commit/3cc6a2b7d68afb5fa47e9bcebf77dc4cdd843d2b). You can now set the language code via the env setting `HC_LANGUAGE_CODE`. The code is in the format of e.g. `de-DE` or `en-US`, like in the `Accept-Language` HTTP header.
